bizeducate_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls", namespace="website")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from .views import (
    index,
    ContactUsView,
    contact_us_success,
    CourseListView,
    CourseDetailView,
    FinanceListView,
    TestimonialListView,
    AuthorCreateView,
    AuthorDetailView,
    AuthorUpdateView,
    AuthorDeleteView,
    TestimonialCreateView,
    TestimonialDeleteView,
    TestimonialUpdateView,
    LawListView,
    CgListView,
    ProjectManagementListView,
    about_us,
    corporate,
)

urlpatterns = [
    path("", index, name="index"),
    path("contact_us/", ContactUsView.as_view(), name="contact-us"),
    path("contact_us_success/", contact_us_success, name='contact_us_success'),
    path("courses/", CourseListView.as_view(), name="course-list"),
    path("courses/<int:pk>/", CourseDetailView.as_view(), name="course-detail"),
    path("testimonials/", TestimonialListView.as_view(), name="testimonial-list"),
    path(
        "testimonials/create/",
        TestimonialCreateView.as_view(),
        name="testimonial-create",
    ),
    path(
        "testimonials/<int:pk>/update/",
        TestimonialUpdateView.as_view(),
        name="testimonial-update",
    ),
    path(
        "testimonials/<int:pk>/delete/",
        TestimonialDeleteView.as_view(),
        name="testimonial-delete",
    ),
    path("authors/create/", AuthorCreateView.as_view(), name="author-create"),
    path("authors/<int:pk>/", AuthorDetailView.as_view(), name="author-detail"),
    path("authors/<int:pk>/update/", AuthorUpdateView.as_view(), name="author-update"),
    path("authors/<int:pk>/delete/", AuthorDeleteView.as_view(), name="author-delete"),
    path("finance/", FinanceListView.as_view(), name="finance-list"),
    path("project-management/", ProjectManagementListView.as_view(), name="project-management-list"),
    path("law/", LawListView.as_view(), name="law-list"),
    path("grc/", CgListView.as_view(), name="grc-list"),
    path("about/", about_us, name="about"),
    path("corporate/", corporate, name="corporate"),
]

app_name = "website"

website/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from django.conf import settings


class Venue(models.Model):
    city = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    venue_image = models.ImageField(null=True, blank=True, upload_to="images/")

    class Meta:
        ordering = ["country"]

    def __str__(self):
        return f"{self.city}, {self.country}"


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Trainer(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    qualification = models.CharField(max_length=500, blank=True)
    profile = models.TextField(max_length=3000, blank=True)
    category = models.ForeignKey(
        Category, on_delete=models.DO_NOTHING, blank=True, related_name="trainers"
    )
    trainer_image = models.ImageField(null=True, blank=True, upload_to="images/")

    def __str__(self):
        return f"Trainer: {self.first_name} {self.last_name}"


class Course(models.Model):
    title = models.CharField(max_length=500, unique=True)
    category = models.ForeignKey(
        Category, on_delete=models.DO_NOTHING, blank=True, related_name="courses"
    )
    venue = models.ForeignKey(
        Venue,
        on_delete=models.DO_NOTHING,
        blank=True,
        null=True,
        related_name="courses",
    )
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    overview = models.TextField(max_length=1500, blank=True)
    learning_outcome = models.TextField(max_length=500, blank=True)
    trainers = models.ManyToManyField(Trainer, related_name="courses")

    class Meta:
        ordering = ["start_date"]

    def __str__(self):
        return self.title


class CourseKeyQuestion(models.Model):
    course = models.ForeignKey(Course, related_name="key_questions", on_delete=models.CASCADE)
    question = models.CharField(max_length=1000)

    def __str__(self):
        return self.question


class CourseAudience(models.Model):
    course = models.ForeignKey(Course, related_name="audience", on_delete=models.CASCADE)
    audience = models.CharField(max_length=500)

    def __str__(self):
        return self.audience


class Author(AbstractUser):

    class Meta:
        ordering = ["first_name"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("website:author-detail", kwargs={"pk": self.pk})


class Testimonial(models.Model):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="testimonials"
    )
    comment = models.TextField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    author_full_name = models.CharField(max_length=255)
    author_company = models.CharField(max_length=255)
    author_position = models.CharField(max_length=255)
    author_company_logo = models.ImageField(null=True, upload_to="logos/")

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return f"{self.author_full_name}: {self.comment}"

website/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django_recaptcha.fields import ReCaptchaField, ReCaptchaV2Checkbox

from website.models import Category, Author, Testimonial


class CourseSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title"}),
    )
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        required=False,
        label="",
        empty_label="Select category",
    )
    city = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by city"}),
    )


class AuthorCreateForm(UserCreationForm):
    class Meta:
        model = Author
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]


class TestimonialCreateForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = [
            "author_full_name",
            "author_position",
            "author_company",
            "comment",
            "author_company_logo",
        ]


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Name'}
    ))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'Email'}
    ))
    company = forms.CharField(max_length=100, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Company'}
    ))
    message = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control', 'placeholder': 'Message'}
    ))
    captcha = ReCaptchaField()

website/views.py
import os

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render
from django.core.mail import send_mail
from django.http import HttpRequest, HttpResponse
from django.views import generic
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from datetime import timedelta


from .forms import (
    CourseSearchForm,
    AuthorCreateForm,
    TestimonialCreateForm,
    ContactForm,
)
from .models import Course, Trainer, Testimonial, Author


def get_one_week_from_now():
    return timezone.now().date() + timedelta(weeks=1)


def index(request: HttpRequest) -> HttpResponse:
    one_week_from_now = get_one_week_from_now()
    courses = Course.objects.filter(start_date__gt=one_week_from_now)[:3]
    testimonials = Testimonial.objects.all()
    context = {
        "courses": courses,
        "testimonials": testimonials,
    }
    return render(request, "website/index.html", context=context)


class ContactUsView(generic.FormView):
    form_class = ContactForm
    template_name = "website/contact_us.html"
    success_url = reverse_lazy('website:contact_us_success')

    def form_valid(self, form):
        send_mail(
            form.cleaned_data["company"],
            f"Message from {form.cleaned_data['name']} <{form.cleaned_data['email']}>\n\n"
            f"{form.cleaned_data['message']}",
            None,  # from email
            [os.getenv("RECIPIENT_EMAIL_ADDRESS")],
        )
        return super().form_valid(form)


def contact_us_success(request: HttpRequest) -> HttpResponse:
    return render(request, 'website/contact_us_success.html')


class CourseListView(generic.ListView):
    model = Course
    queryset = Course.objects.all()
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(CourseListView, self).get_context_data(**kwargs)
        categories = set(course.category for course in context["course_list"])
        title = self.request.GET.get("title", "")
        category = self.request.GET.get("category", "")
        city = self.request.GET.get("city", "")
        context.update(
            {
                "trainers": Trainer.objects.filter(category__in=categories),
                "search_form": CourseSearchForm(
                    initial={"title": title, "category": category, "city": city}
                ),
            }
        )
        return context

    def get_queryset(self):
        one_week_from_now = get_one_week_from_now()
        queryset = Course.objects.filter(start_date__gt=one_week_from_now)
        form = CourseSearchForm(self.request.GET)
        if form.is_valid():
            title_query = form.cleaned_data.get("title", "")
            category_query = form.cleaned_data.get("category")
            city_query = form.cleaned_data.get("city", "")

            if title_query:
                queryset = queryset.filter(title__icontains=title_query)
            if category_query:
                queryset = queryset.filter(category=category_query)
            if city_query:
                queryset = queryset.filter(venue__city__icontains=city_query)

        return queryset


class CourseDetailView(generic.DetailView):
    model = Course


class TestimonialListView(generic.ListView):
    model = Testimonial
    template_name = "website/testimonial_list.html"
    paginate_by = 5


class TestimonialCreateView(LoginRequiredMixin, generic.CreateView):
    model = Testimonial
    form_class = TestimonialCreateForm
    success_url = reverse_lazy("website:testimonial-list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class TestimonialUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Testimonial
    fields = ["author_full_name", "author_company", "comment", "author_company_logo"]

    def get_success_url(self):
        return reverse_lazy(
            "website:author-detail", kwargs={"pk": self.object.owner.pk}
        )


class TestimonialDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Testimonial

    def get_success_url(self):
        return reverse_lazy(
            "website:author-detail", kwargs={"pk": self.object.owner.pk}
        )


class AuthorCreateView(generic.CreateView):
    model = Author
    form_class = AuthorCreateForm
    template_name = "website/author_form.html"

    def form_valid(self, form):
        response = super().form_valid(form)
        self.object.set_password(form.cleaned_data["password1"])
        self.object.save()
        return response

    def get_success_url(self):
        return reverse("website:author-detail", kwargs={"pk": self.object.pk})


class AuthorUpdateView(generic.UpdateView):
    model = Author
    fields = ["first_name", "last_name", "email"]

    def get_success_url(self):
        return self.object.get_absolute_url()


class AuthorDetailView(generic.DetailView):
    model = Author
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        testimonials = Testimonial.objects.filter(owner=self.object)
        paginator = Paginator(testimonials, self.paginate_by)
        page_number = self.request.GET.get("page")

        try:
            page_obj = paginator.page(page_number)
        except PageNotAnInteger:
            page_obj = paginator.page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)

        context["testimonials"] = page_obj
        context["paginator"] = paginator
        context["page_obj"] = page_obj
        context["is_paginated"] = page_obj.has_other_pages()
        return context


class AuthorDeleteView(generic.DeleteView):
    model = Author
    template_name = "website/author_delete_confirmation.html"
    success_url = reverse_lazy("website:index")


class FinanceListView(CourseListView):
    template_name = "website/finance_list.html"

    def get_queryset(self):
        return super().get_queryset().filter(category__name__iexact="finance")


class ProjectManagementListView(CourseListView):
    template_name = "website/project_management_list.html"

    def get_queryset(self):
        return super().get_queryset().filter(category__name__iexact="project management")


class LawListView(CourseListView):
    template_name = "website/law_list.html"

    def get_queryset(self):
        return super().get_queryset().filter(category__name__iexact="corporate law")


class CgListView(CourseListView):
    template_name = "website/grc_list.html"

    def get_queryset(self):
        return (
            super().get_queryset().filter(category__name__iexact="grc")
        )


def about_us(request: HttpRequest) -> HttpResponse:
    testimonials = Testimonial.objects.all()
    context = {
        "testimonials": testimonials,
    }
    return render(request, "website/about_us.html", context=context)


def corporate(request: HttpRequest) -> HttpResponse:
    return render(request, "website/corporate_training.html")

templates/website/author_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- Hero -->
  <section class="module parallax text-center" data-background="{% static 'images/london2_1280-compressed.jpg' %}" data-overlay="0.6">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-6 m-auto">
          <div class="m-b-20">
            <h2>Account profile</h2>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Hero end -->

  <!-- Profile details -->
  <section class="bg-light">
    <div class="container">
      <div class="row pt-3">
        <div class="col-lg-6 col-md-8 m-auto">
          <div class="m-b-20 m-t-20">
            <h4 class="pb-3">{{ author.first_name }} {{ author.last_name }}</h4>
            <p class="lead"><span class="text-uppercase">Username:</span> {{ author.username }}</p>
            <p class="lead"><span class="text-uppercase">Email:</span> {{ author.email }}</p>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="space" data-MY="60px"></div>
      </div>
      <div class="form-row col-lg-8 col-md-10 m-auto">
        <div class="form-group col-md-4">
          <a class="btn btn-block btn-round btn-brand" href="{% url 'website:author-update' pk=author.id %}">Edit profile</a>
        </div>
        <div class="form-group col-md-4">
          <a class="btn btn-block btn-round btn-success"  href="{% url 'website:testimonial-create' %}">Create feedback</a>
        </div>
        <div class="form-group col-md-4">
          <a class="btn btn-block btn-round btn-danger"  href="{% url 'website:author-delete' pk=author.id %}">Delete profile</a>
        </div>
      </div>
    </div>
  </section>
  <!-- Profile details end -->

  <!-- List of author's testimonials -->
  {% if testimonials %}
    <section>
    <div class="container mt-5 mb-5">
      <div class="row">
        <div class="col-lg-4 col-md-6 m-auto">
          <div class="m-b-20">
            <h3>Published testimonials:</h3>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 m-auto text-left">
          <div class="row row-post-thumbnail">
            <!-- Testimonial-->
            {% for testimonial in testimonials %}
              <article class="post row align-items-start mb-0 pt-3">
                <div class="col-md-5">
                  <div class="post-preview w-50 h-50 d-flex m-auto"><img src="{{ testimonial.author_company_logo.url }}" class="img-fluid" alt="logo"></div>
                </div>
                <div class="col-md-7">
                  <blockquote class="blockquote mb-0">
                    <p>{{ testimonial.comment }}</p>
                    <footer class="blockquote-footer">{{ testimonial.author_full_name}}, {{ testimonial.author_position }} at {{ testimonial.author_company }}
                      <p>{{ testimonial.date|date:"d M Y" }}</p>
                    </footer>
                  </blockquote>
                </div>
              </article>
              <div class="form-row m-auto pb-5">
                <div class="form-group col-md-6 col-sm-6">
                  <a class="btn btn-outline-secondary btn-sm" href="{% url 'website:testimonial-update' pk=testimonial.id %}">Edit</a>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                  <a class="btn btn-outline-danger btn-sm" href="{% url 'website:testimonial-delete' pk=testimonial.id %}">Delete</a>
                </div>
              </div>
            {% endfor %}
              <!-- Testimonial end-->
          </div>
        </div>
      </div>
    </div>
    {% block pagination %}
      {% include 'includes/pagination.html' %}
    {% endblock %}
  </section>
  {% endif %}
  <!-- List of author's testimonials end -->
{% endblock %}

templates/website/author_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% load static %}

{% block content %}
  <section class="module parallax text-center" data-background="{% static 'images/nyc_1280-compressed.jpg' %}" data-overlay="0.6">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-6 m-auto">
          <div class="m-b-20">
            <h3>{{ object|yesno:"Update,Create" }} account</h3>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-8 m-auto">
          <div class="m-b-20 m-t-20">
            <form action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form|crispy }}
              <button class="btn btn-block btn-round btn-brand w-50 m-auto" type="submit">Submit</button>
            </form>
          </div>
          <div class="m-b-20">
            <p><small>By signing up, you agree to the <a href="#">terms of service</a></small></p>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

templates/website/cg_list.html
{% extends "base.html" %}

{% load static %}
{% block title %} <title>Corporate Governance</title> {% endblock %}

{% block content %}

  <!-- Page Header-->
  <section class="module-cover parallax text-center" data-background="{% static 'images/corp_governance_1280-compressed.jpg' %}" data-overlay="0.5">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-9 m-auto text-center">
          <h2>Corporate Governance</h2>
          <p class="lead">Bizeducate offers corporate governance training courses covering the essential skills and best practices for all Company Directors and Company Secretaries, as well as other senior managers of the business.</p>
        </div>
      </div>
    </div>
  </section>
  <!-- Page Header end-->

  <!--Course list-->
  <div class="container mt-5 mb-5">
    {% if course_list %}
      <table class="table lead">
        <tr>
          <th>Title</th>
          <th>City</th>
          <th>Start Date</th>
        </tr>
        {% for course in course_list %}
          <tr>
            <td><a href="{% url 'website:course-detail' pk=course.id %}">{{ course.title }}</a>
              <p>{{ course.overview|truncatechars:300 }}</p>
            </td>
            <td>{{ course.venue.city }}</td>
            <td>{{ course.start_date|date:"d M Y" }}</td>
          </tr>
        {% endfor %}
      </table>
    {% else %}
      <p>Sorry, we don't have any courses in the list now.</p>
    {% endif %}
  </div>
  <!-- Course list end -->

  <!--Trainers list-->
   <div class="module">
    <div class="container">
      <div class="row mb-5">
        <div class="col-lg-8 m-auto">
          <h3>Governance specialists who deliver our courses:</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-10 m-auto">
          {% for trainer in trainers %}
            <div class="media">
              <img src="{{ trainer.trainer_image.url }}" class="mr-3" style="width: 200px; height: auto" alt="trainer">
              <div class="media-body pl-3">
                <h5 class="mt-0">{{ trainer.first_name }} {{ trainer.last_name }}</h5>
                <p>{{ trainer.profile }}</p>
              </div>
            </div>
            <div class="col-md-12">
              <hr class="m-t-40 m-b-30">
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <!-- Trainers list end-->

{% endblock %}

templates/website/finance_list.html
{% extends "base.html" %}

{% load static %}
{% block title %} <title>Finance</title> {% endblock %}

{% block content %}

  <!-- Page Header-->
  <section class="module-cover parallax text-center" data-background="{% static 'images/finance_1280-compressed.jpg' %}" data-overlay="0.5">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-9 m-auto text-center">
          <h2>Financial Courses</h2>
          <p class="lead">Bizeducate’s portfolio of finance high level courses covers the essential themes and issues surrounding accounting, budgeting, auditing, risk-management and more.</p>
        </div>
      </div>
    </div>
  </section>
  <!-- Page Header end-->

  <!--Course list-->
  <div class="container mt-5 mb-5">
    {% if course_list %}
      <table class="table lead">
        <tr>
          <th>Title</th>
          <th>City</th>
          <th>Start Date</th>
        </tr>
        {% for course in course_list %}
          <tr>
            <td><a href="{% url 'website:course-detail' pk=course.id %}">{{ course.title }}</a>
              <p>{{ course.overview|truncatechars:300 }}</p>
            </td>
            <td>{{ course.venue.city }}</td>
            <td>{{ course.start_date|date:"d M Y" }}</td>
          </tr>
        {% endfor %}
      </table>
    {% else %}
      <p>Sorry, we don't have any courses in the list now.</p>
    {% endif %}
  </div>
  <!-- Course list end -->

  <!--Trainers list-->
   <div class="module">
    <div class="container">
      <div class="row mb-5">
        <div class="col-lg-8 m-auto">
          <h3>Financial specialists who deliver our courses:</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-10 m-auto">
          {% for trainer in trainers %}
            <div class="media">
              <img src="{{ trainer.trainer_image.url }}" class="mr-3" style="width: 200px; height: auto" alt="trainer">
              <div class="media-body pl-3">
                <h5 class="mt-0">{{ trainer.first_name }} {{ trainer.last_name }}</h5>
                <p>{{ trainer.profile }}</p>
              </div>
            </div>
            <div class="col-md-12">
              <hr class="m-t-40 m-b-30">
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <!-- Trainers list end-->

{% endblock %}

templates/website/grc_list.html
{% extends "base.html" %}

{% load static %}
{% block title %} <title>GRC</title> {% endblock %}

{% block content %}

  <!-- Page Header-->
  <section class="module-cover parallax text-center" data-background="{% static 'images/corp_governance_1280-compressed.jpg' %}" data-overlay="0.5">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-9 m-auto text-center">
          <h2>Governance, Risk, and Compliance</h2>
          <p class="lead">Master the essentials of Governance, Risk, and Compliance (GRC) with our expert-led courses designed to help professionals navigate regulations, manage risk, and build resilient organisations.</p>
        </div>
      </div>
    </div>
  </section>
  <!-- Page Header end-->

  <!--Course list-->
  <div class="container mt-5 mb-5">
    {% if course_list %}
      <table class="table lead">
        <tr>
          <th>Title</th>
          <th>City</th>
          <th>Start Date</th>
        </tr>
        {% for course in course_list %}
          <tr>
            <td><a href="{% url 'website:course-detail' pk=course.id %}">{{ course.title }}</a>
              <p>{{ course.overview|truncatechars:300 }}</p>
            </td>
            <td>{{ course.venue.city }}</td>
            <td>{{ course.start_date|date:"d M Y" }}</td>
          </tr>
        {% endfor %}
      </table>
    {% else %}
      <p>Sorry, we don't have any courses in the list now.</p>
    {% endif %}
  </div>
  <!-- Course list end -->

  <!--Trainers list-->
   <div class="module">
    <div class="container">
      <div class="row mb-5">
        <div class="col-lg-8 m-auto">
          <h3>GRC experts who deliver our courses:</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-10 m-auto">
          {% for trainer in trainers %}
            <div class="media">
              <img src="{{ trainer.trainer_image.url }}" class="mr-3" style="width: 200px; height: auto" alt="trainer">
              <div class="media-body pl-3">
                <h5 class="mt-0">{{ trainer.first_name }} {{ trainer.last_name }}</h5>
                <p>{{ trainer.profile }}</p>
              </div>
            </div>
            <div class="col-md-12">
              <hr class="m-t-40 m-b-30">
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <!-- Trainers list end-->

{% endblock %}

templates/website/hr_list.html
{% extends "base.html" %}

{% load static %}
{% block title %} <title>HR</title> {% endblock %}

{% block content %}

  <!-- Page Header-->
  <section class="module-cover parallax text-center" data-background="{% static 'images/hr_1280-compressed.jpg' %}" data-overlay="0.5">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-9 m-auto text-center">
          <h2>HR Courses</h2>
          <p class="lead">Bizeducate has been delivering HR training for a number of years. Our programmes encourage critical reflection on current developments and focus on contemporary issues in HR.</p>
        </div>
      </div>
    </div>
  </section>
  <!-- Page Header end-->

  <!--Course list-->
  <div class="container mt-5 mb-5">
    {% if course_list %}
      <table class="table lead">
        <tr>
          <th>Title</th>
          <th>City</th>
          <th>Start Date</th>
        </tr>
        {% for course in course_list %}
          <tr>
            <td><a href="{% url 'website:course-detail' pk=course.id %}">{{ course.title }}</a>
              <p>{{ course.overview|truncatechars:300 }}</p>
            </td>
            <td>{{ course.venue.city }}</td>
            <td>{{ course.start_date|date:"d M Y" }}</td>
          </tr>
        {% endfor %}
      </table>
    {% else %}
      <p>Sorry, we don't have any courses in the list now.</p>
    {% endif %}
  </div>
  <!-- Course list end -->

  <!--Trainers list-->
   <div class="module">
    <div class="container">
      <div class="row mb-5">
        <div class="col-lg-8 m-auto">
          <h3>HR specialists who deliver our courses:</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-10 m-auto">
          {% for trainer in trainers %}
            <div class="media">
              <img src="{{ trainer.trainer_image.url }}" class="mr-3" style="width: 200px; height: auto" alt="trainer">
              <div class="media-body pl-3">
                <h5 class="mt-0">{{ trainer.first_name }} {{ trainer.last_name }}</h5>
                <p>{{ trainer.profile }}</p>
              </div>
            </div>
            <div class="col-md-12">
              <hr class="m-t-40 m-b-30">
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <!-- Trainers list end-->

{% endblock %}