bizeducate_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls", namespace="website")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from .views import (
    index,
    ContactUsView,
    contact_us_success,
    CourseListView,
    CourseDetailView,
    FinanceListView,
    TestimonialListView,
    AuthorCreateView,
    AuthorDetailView,
    AuthorUpdateView,
    AuthorDeleteView,
    TestimonialCreateView,
    TestimonialDeleteView,
    TestimonialUpdateView,
    LawListView,
    CgListView,
    ProjectManagementListView,
    about_us,
    corporate,
)

urlpatterns = [
    path("", index, name="index"),
    path("contact_us/", ContactUsView.as_view(), name="contact-us"),
    path("contact_us_success/", contact_us_success, name='contact_us_success'),
    path("courses/", CourseListView.as_view(), name="course-list"),
    path("courses/<int:pk>/", CourseDetailView.as_view(), name="course-detail"),
    path("testimonials/", TestimonialListView.as_view(), name="testimonial-list"),
    path(
        "testimonials/create/",
        TestimonialCreateView.as_view(),
        name="testimonial-create",
    ),
    path(
        "testimonials/<int:pk>/update/",
        TestimonialUpdateView.as_view(),
        name="testimonial-update",
    ),
    path(
        "testimonials/<int:pk>/delete/",
        TestimonialDeleteView.as_view(),
        name="testimonial-delete",
    ),
    path("authors/create/", AuthorCreateView.as_view(), name="author-create"),
    path("authors/<int:pk>/", AuthorDetailView.as_view(), name="author-detail"),
    path("authors/<int:pk>/update/", AuthorUpdateView.as_view(), name="author-update"),
    path("authors/<int:pk>/delete/", AuthorDeleteView.as_view(), name="author-delete"),
    path("finance/", FinanceListView.as_view(), name="finance-list"),
    path("project-management/", ProjectManagementListView.as_view(), name="project-management-list"),
    path("law/", LawListView.as_view(), name="law-list"),
    path("grc/", CgListView.as_view(), name="grc-list"),
    path("about/", about_us, name="about"),
    path("corporate/", corporate, name="corporate"),
]

app_name = "website"

templates/includes/clients.html
{% load static %}

<div class="row m-t-40">
  <div class="col-md-8 m-auto text-center">
    <div class="owl-carousel clients-carousel">
       <div class="client"><img src="{% static "images/clients/socar.png" %}" alt=""></div>
       <div class="client"><img src="{% static "images/clients/brk.gif" %}" alt=""></div>
       <div class="client"><img src="{% static "images/clients/tengizchevroil.png" %}" alt=""></div>
       <div class="client"><img src="{% static "images/clients/KazMunaiGaz.png" %}" alt=""></div>
       <div class="client"><img src="{% static "images/clients/kazpost.png" %}" alt=""></div>
       <div class="client"><img src="{% static "images/clients/ktz.png" %}" alt=""></div>
       <div class="client"><img src="{% static "images/clients/SOFAZ.png" %}" alt=""></div>
    </div>
  </div>
</div>

templates/includes/corp_training_offer.html
{% load static %}

<section class="module-cover parallax text-center pt-5 pb-5" data-background="{% static "images/london_city_1920-compressed.jpg" %}" data-overlay="0.5">
   <div class="container">
       <div class="row">
           <div class="col-md-12">
               <h2>Looking For An Exclusive Corporate Training?</h2>
               <p class="lead">We will incorporate your inquiries and needs.</p>
           </div>
       </div>
       <div class="row mt-5">
           <div class="col-md-12 m-auto text-center">
               <p><a class="btn btn-circle btn-brand" href="{% url "website:corporate" %}">FIND OUT MORE</a>
           </div>
       </div>
   </div>
</section>

templates/includes/counters.html
{% load static %}
<section class="module-cover parallax text-center pb-5 pt-5" data-background="{% static "images/london-1-compressed.jpg" %}" data-overlay="0.6">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <div class="counter">
              <div class="counter-icon"><span class="icon-energy icons"></span></div>
              <div class="counter-number">
                <h6><strong class="counter-timer" data-from="0" data-to="350">0</strong></h6>
              </div>
              <div class="counter-title">Organised Courses</div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="counter">
              <div class="counter-icon"><span class="icon-mustache icons"></span></div>
              <div class="counter-number">
                <h6><strong class="counter-timer" data-from="0" data-to="1160">0</strong></h6>
              </div>
              <div class="counter-title">Participated Professionals</div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="counter">
              <div class="counter-icon"><span class="icon-fire icons"></span></div>
              <div class="counter-number">
                <h6><strong class="counter-timer" data-from="0" data-to="11">0</strong></h6>
              </div>
              <div class="counter-title">Countries of Organised Trainings</div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="counter">
              <div class="counter-icon"><span class="icon-diamond icons"></span></div>
              <div class="counter-number">
                <h6><strong class="counter-timer" data-from="0" data-to="14">0</strong></h6>
              </div>
              <div class="counter-title">Years on Market</div>
            </div>
          </div>
        </div>
      </div>
</section>

templates/includes/courses_categories.html
<section class="module divider-bottom">
  <div class="container">
    <div class="row">
      <div class="col-md-6 m-auto text-center">
        <h2>Areas of Our Courses</h2>
        <p class="lead">Discover the Wide Array of Expertise Covered in Our Course Offerings.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="space" data-MY="60px"></div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-6">
        <div class="icon-box text-center">
          <div class="icon-box-icon"><span class="ti-money"></span></div>
          <div class="icon-box-title">
            <h6>Finance</h6>
          </div>
          <div class="icon-box-content">
            <p>Our comprehensive courses tailored to professionals seeking to master financial analysis, risk management, and strategic decision-making.</p>
          </div>
          <div class="icon-box-link"><a href="{% url 'website:finance-list' %}">Read more</a></div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="icon-box text-center">
          <div class="icon-box-icon"><span class="ti-dashboard"></span></div>
          <div class="icon-box-title">
            <h6>Project Management</h6>
          </div>
          <div class="icon-box-content">
            <p>Build confidence in planning, budgeting, and leading construction projects with courses focused on practical skills and real-world application.</p>
          </div>
          <div class="icon-box-link"><a href="{% url "website:project-management-list" %}">Read more</a></div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="icon-box text-center">
          <div class="icon-box-icon"><span class="ti-briefcase"></span></div>
          <div class="icon-box-title">
            <h6>Corporate Law</h6>
          </div>
          <div class="icon-box-content">
            <p>Boost your legal skills with our corporate law courses, covering business regulations, corporate structures, contracts, arbitration, and governance strategies.</p>
          </div>
          <div class="icon-box-link"><a href="{% url "website:law-list" %}">Read more</a></div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="icon-box text-center">
          <div class="icon-box-icon"><span class="ti-pie-chart"></span></div>
          <div class="icon-box-title">
            <h6>GRC</h6>
          </div>
          <div class="icon-box-content">
            <p>Learn essential GRC skills with our practical courses, empowering you to manage risk, ensure compliance, and strengthen organisational governance.</p>
          </div>
          <div class="icon-box-link"><a href="{% url "website:grc-list" %}">Read more</a></div>
        </div>
      </div>
    </div>
  </div>
</section>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}

    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>

    {% endif %}
  </ul>
{% endif %}

templates/includes/slider.html
{% load static %}
   <section class="module-cover-slides fullscreen">
      <ul class="slides-container">
        <li class="parallax text-center" data-overlay="0.5"><img src="{% static "images/skyline_london-compressed.jpg" %}" alt="london">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <h1 class="m-b-20"><strong>Empowering Minds, <br> Transforming Lives:</strong></h1>
                <h4 class="m-b-40">Go Global With Our Courses</h4>
                <p><a class="btn btn-lg btn-circle btn-brand" href="{% url "website:course-list" %}">List of events</a></p>
              </div>
            </div>
          </div>
        </li>
        <li class="parallax text-center" data-overlay="0.5"><img src="{% static "images/tower-bridge-compressed.jpg" %}" alt="london">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <h1 class="m-b-20"><strong>Corporate Training</strong></h1>
                <h4 class="m-b-40">Unlock Your Team's Potential with Custom Corporate Courses.</h4>
                <p><a class="btn btn-lg btn-circle btn-brand" href="{% url "website:contact-us" %}">Discuss</a><a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url "website:corporate" %}">Learn More</a></p>
              </div>
            </div>
          </div>
        </li>
      </ul>
      <div class="slides-navigation"><a class="prev" href="#"><span class="ti-angle-left"></span></a><a class="next" href="#"><span class="ti-angle-right"></span></a></div>
    </section>

templates/includes/testimonials_homepage.html
<section class="module bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-6 m-auto text-center">
        <h2>What Our Customers Say</h2>
        <p class="lead">Our goal is to increase your professional expertise. We’ll do our best so that the result of training in BizEducate exceeds your expectations.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="space" data-MY="60px"></div>
      </div>
    </div>
    <div class="owl-carousel review-carousel">
      {% for testimonial in testimonials %}
      <div class="review-card">
        <div class="review-card-content">
           <p>{{ testimonial.comment }}</p>
        </div>
        <div class="review-card-author">
          {% if testimonial.author_company_logo %}
            <div class="w-50 h-50 d-flex m-auto">
              <img src="{{ testimonial.author_company_logo.url }}" class="img-fluid" alt="logo">
            </div>
            <div class="review-card-author-info mt-3">
              <h6 class="review-card-author-title">{{ testimonial.author_full_name }}</h6>
              <p>{{ testimonial.author_position }} | {{ testimonial.author_company }}</p>
            </div>
          {% else %}
            <div class="review-card-author-info">
              <h6 class="review-card-author-title">{{ testimonial.author_full_name }}</h6>
              <p>{{ testimonial.author_position }} | {{ testimonial.author_company }}</p>
            </div>
          {% endif %}
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="row mt-5">
      <div class="col-md-3 m-auto text-center">
        <p><a class="btn btn-circle btn-brand" href="{% url 'website:testimonial-list' %}">ALL TESTIMONIALS</a>
      </div>
    </div>
  </div>
</section>

templates/includes/upcoming_events.html
{% load static %}
<section class="module">
  <div class="container">
    <div class="row">
      <div class="col-md-6 m-auto text-center">
        <h2>Upcoming Events</h2>
        <p class="lead">Stay Ahead of the Curve: Preview Our Upcoming Events and Workshops.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="space" data-MY="60px"></div>
      </div>
    </div>
    <div class="row row-post-masonry">
      {% for course in courses %}
        <div class="col-md-4 post-item">
          <!-- Post-->
          <article class="post">
            <div class="post-preview"><a href="{% url 'website:course-detail' pk=course.id %}"><img src="{{ course.venue.venue_image.url }}" style="width: 800px; max-height: 600px;" alt="city"></a></div>
            <div class="post-wrapper">
              <div class="post-header">
                <h2 class="post-title"><a href="{% url 'website:course-detail' pk=course.id %}">{{ course.title }}</a></h2>
              </div>
              <div class="post-content">
                <p>{{  course.venue }} | {{  course.start_date|date:"d M Y" }}</p>
                <p>{{ course.overview|truncatechars:200 }}</p>
                <p><a href="{% url 'website:course-detail' pk=course.id %}">Read more</a></p>
              </div>
            </div>
          </article>
        </div>
      {% endfor %}
    </div>
    <div class="row mt-5">
      <div class="col-md-3 m-auto text-center">
        <p><a class="btn btn-circle btn-brand" href="{% url 'website:course-list' %}">ALL COURSES</a>
      </div>
    </div>
  </div>
</section>