bizeducate_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls", namespace="website")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from .views import (
    index,
    ContactUsView,
    contact_us_success,
    CourseListView,
    CourseDetailView,
    FinanceListView,
    TestimonialListView,
    AuthorCreateView,
    AuthorDetailView,
    AuthorUpdateView,
    AuthorDeleteView,
    TestimonialCreateView,
    TestimonialDeleteView,
    TestimonialUpdateView,
    LawListView,
    CgListView,
    ProjectManagementListView,
    about_us,
    corporate,
)

urlpatterns = [
    path("", index, name="index"),
    path("contact_us/", ContactUsView.as_view(), name="contact-us"),
    path("contact_us_success/", contact_us_success, name='contact_us_success'),
    path("courses/", CourseListView.as_view(), name="course-list"),
    path("courses/<int:pk>/", CourseDetailView.as_view(), name="course-detail"),
    path("testimonials/", TestimonialListView.as_view(), name="testimonial-list"),
    path(
        "testimonials/create/",
        TestimonialCreateView.as_view(),
        name="testimonial-create",
    ),
    path(
        "testimonials/<int:pk>/update/",
        TestimonialUpdateView.as_view(),
        name="testimonial-update",
    ),
    path(
        "testimonials/<int:pk>/delete/",
        TestimonialDeleteView.as_view(),
        name="testimonial-delete",
    ),
    path("authors/create/", AuthorCreateView.as_view(), name="author-create"),
    path("authors/<int:pk>/", AuthorDetailView.as_view(), name="author-detail"),
    path("authors/<int:pk>/update/", AuthorUpdateView.as_view(), name="author-update"),
    path("authors/<int:pk>/delete/", AuthorDeleteView.as_view(), name="author-delete"),
    path("finance/", FinanceListView.as_view(), name="finance-list"),
    path("project-management/", ProjectManagementListView.as_view(), name="project-management-list"),
    path("law/", LawListView.as_view(), name="law-list"),
    path("grc/", CgListView.as_view(), name="grc-list"),
    path("about/", about_us, name="about"),
    path("corporate/", corporate, name="corporate"),
]

app_name = "website"

templates/base.html
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  {% block title %}
  {% endblock %}

  {% load static %}

  <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600%7cPlayfair+Display:400i" rel="stylesheet">
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static "css/plugins.min.css" %}">
  <link rel="stylesheet" href="{% static "css/template.css" %}">
  <link rel="stylesheet" href="{% static "css/custom.css" %}">
  <link rel="icon" type="image/png" href="{% static 'images/favicon-biz.32x32.png' %}">



</head>
<body>
<!-- Preloader-->
  <div class="page-loader">
    <div class="page-loader-inner">
      <div class="spinner">
        <div class="double-bounce1"></div>
        <div class="double-bounce2"></div>
      </div>
    </div>
  </div>
<!-- Preloader end-->

<!-- Header-->
  <header class="header header-transparent">
    <div class="container-fluid">
      <!-- Brand-->
      <div class="inner-header"><a class="inner-brand" href="{% url "website:index" %}">Bizeducate</a></div>
      <!-- Navigation-->
      <div class="inner-navigation collapse">
        <div class="inner-nav">
          <ul>
            <li class="menu-item-has-children"><a href="{% url "website:about" %}"><span class="menu-item-span">About</span></a>
              <ul class="sub-menu">
                <li class="menu-item-span"><a href="{% url "website:testimonial-list" %}">Testimonials</a></li>
              </ul>
            </li>
            <li class="menu-item-has-children"><a href="{% url 'website:course-list' %}"><span class="menu-item-span">Open Courses</span></a>
              <ul class="sub-menu">
                <li class="menu-item-span"><a href="{% url "website:finance-list" %}">Finance</a>
                </li>
                <li class="menu-item-span"><a href="{% url "website:project-management-list" %}">Project Management</a>
                </li>
                <li class="menu-item-span"><a href="{% url "website:law-list" %}">Corporate Law</a>
                </li>
                <li class="menu-item-span"><a href="{% url "website:grc-list" %}">GRC</a>
                </li>
              </ul>
            </li>
            <li><a href="{% url "website:corporate" %}"><span class="menu-item-span">Corporate Training</span></a>
            </li>
            <li><a href="{% url "website:contact-us" %}"><span class="menu-item-span">Contact Us</span></a>
            </li>
            <!-- For mobile devices -->
            {% if user.is_authenticated %}
              <li class="menu-item-has-children d-lg-none">
                <a href="#">
                  <span class="menu-item-span">{{ user.get_username }}</span>
                </a>
                <ul class="sub-menu">
                  <li><a href="{% url 'website:author-detail' pk=user.id %}">Profile</a></li>
                  <li><a href="{% url 'logout'%}">Logout</a></li>
                </ul>
              </li>
            {% else %}
              <li class="menu-item-has-children d-lg-none">
                <a href="{% url 'login' %}">
                  <span class="menu-item-span">Login</span>
                </a>
                <ul class="sub-menu">
                  <li><a href="{% url "website:author-create" %}">Register</a></li>
                </ul>
              </li>
            {% endif %}
            <!-- For mobile devices end -->
          </ul>
        </div>
      </div>
      <!-- For desktop -->
      <div class="inner-nav float-right p-0 d-none d-lg-inline-block">
        <ul>
          {% if user.is_authenticated %}
            <li class="menu-item-has-children">
              <a href="#">
                <span class="menu-item-span">{{ user.get_username }}</span>
              </a>
              <ul class="sub-menu">
                <li><a href="{% url 'website:author-detail' pk=user.id %}">Profile</a> </li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
              </ul>
            </li>
          {% else %}
            <li class="menu-item-has-children">
              <a href="{% url 'login' %}">
                <span class="menu-item-span">Login</span>
              </a>
              <ul class="sub-menu">
                <li><a href="{% url "website:author-create" %}">Register</a></li>
              </ul>
            </li>
          {% endif %}
        </ul>
      </div>
      <!-- For desktop end -->

      <!-- Extra nav-->
      <div class="extra-nav">
        <ul>
          <li class="nav-toggle">
            <a href="#" data-toggle="collapse" data-target=".inner-navigation"><span class="menu-item-span"><i class="ti-menu"></i></span></a>
          </li>
        </ul>
      </div>
      <!-- Extra nav end -->
    </div>
  </header>

<!-- Header end-->
<!-- Wrapper-->
  <div class="wrapper">
    {% block content %}
    {% endblock %}
  
  <!-- Footer-->
    <footer class="footer">
      <div class="footer-widgets">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <!-- Text widget-->
              <aside class="widget widget-text">
                <div class="widget-title">
                  <h6>About Us</h6>
                </div>
                <div class="textwidget">
                  <p>We organise trainings around the globe.</p>
                </div>
                <div class="textwidget pt-3">
                  <img src="{% static "images/logo_bizeducate_transparent_white.png" %}" alt="logo">
                </div>
              </aside>
            </div>
            <div class="col-md-4">
              <!-- Quick links widget-->
              <aside class="widget widget-recent-entries">
                <div class="widget-title">
                  <h6>Quick Links</h6>
                </div>
                <ul>
                  <li><a href="{% url "website:about" %}">About</a></li>
                  <li><a href="{% url "website:course-list" %}">Open Courses</a></li>
                  <li><a href="{% url "website:corporate" %}">Corporate Training</a></li>
                  <li><a href="{% url "website:contact-us" %}">Contact Us</a></li>
                </ul>
              </aside>
            </div>
            <div class="col-md-4">
              <!-- Twitter widget-->
              <aside class="widget twitter-feed-widget">
                <div class="widget-title">
                  <h6>Contact</h6>
                </div>
                <div class="textwidget">
                  <p>
                    Location: 124 City Road, London, EC1 2NX, United Kingdom<br>
                    E-mail: office@bizeducate.com<br>
                    London: +4420 3695 3407<br>
                  </p>
                </div>
              </aside>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-bar">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="copyright">
                <p>© 2008-2025 Bizeducate Ltd., All Rights Reserved.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- Footer end-->
  </div>
  <!-- Wrapper end-->

  <!-- To top button--><a class="scroll-top" href="#top"><i class="fas fa-angle-up"></i></a>

<script src="{% static 'js/custom/jquery.min.js' %}"></script>
<script src="{% static 'js/custom/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'js/custom/plugins.min.js' %}"></script>
<script src="{% static 'js/custom/custom.min.js' %}"></script>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
</body>
</html>